{% set name = "matrix-py3" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f6800ae6dc6941b67e9e61b42ffe97d02a477ebae610dd4e2280672d2e90aae8

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ncurses

test:
  imports:
    - matrix3
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/chunribu/matrix-py3/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python3 implementation of cmatrix with a timer

extra:
  recipe-maintainers:
    - chunribu
